### ISSUE TITLE
CobiGen passes null for classObject

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1117]
### Expected behavior

As a CobiGen-User, I customized my templates calling specific custom Java code that takes `classObject` as input to resolve generic types or make specific decisions what is otherwise not possible with freemarker. This was working in former versions of CobiGen.

### Actual behavior

Since the new public CobiGen release, I am facing a bug that CobiGen is passing `null` for the variable `classObject`.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create custom `CobiGen_Templates` project.
2. Create the following class in `CobiGen_Templates/src/main/java/com.example.cobigen`:
```
package com.example.cobigen;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
public class ReflectionHelper {
  private static final Logger LOG = LoggerFactory.getLogger(ReflectionHelper.class);
  public static void createBean(Class<?> type) {
    LOG.info("Type is {}", type);
  }
}
```
3. Inside one of your Java templates triggered from a Java Input-File (in my Case an ETO class) do this:
```
<#assign bean = ReflectionHelper.createBean(classObject)>
```

This leads me to this output in `CobiGen.log`:
```
2020-03-13 14:47:58,741 [ModalContext] [] INFO  com.capgemini.cobigen.custom.java.ReflectionHelper - Type is null
```

### Related/Dependent Issues
-

### Comments/Hints:
CobiGen code looks sane:
* https://github.com/devonfw/cobigen/blob/master/cobigen/cobigen-javaplugin-parent/cobigen-javaplugin-model/src/main/java/com/devonfw/cobigen/javaplugin/model/ModelConstant.java#L25
* https://github.com/devonfw/cobigen/blob/dev_core/cobigen/cobigen-javaplugin-parent/cobigen-javaplugin/src/main/java/com/devonfw/cobigen/javaplugin/inputreader/ReflectedJavaModelBuilder.java#L97

Any ideas what could be the source of this problem?

### Affected version:

* OS: Mac

**Comment by maybeec** [comment]
How did you execute the generation? Within eclipse? Which version of cobigen did you use?

**Comment by MikeSchumacherCapgemini** [comment]
After testing in the Devon IDE, the dev version of cobigen and a fresh eclipse installation, this problem has not occured the way you are describing.
Steps taken on each:
- Import default mythaistarjava devon example project
- From the cobigen context menu, adapt templates and confirm each step
- Add a new increment as per Cobigen definitions, triggering on ETOs
- Add ReflectionHelper util class
- Add template calling reflectionhelper and classobject directly
- Open Cobigen context menu from an ETO class and generate the new increment

No NPE occured, the template generated as intended.
Perhaps you can check if you still have this problem?

**Comment by hohwille** [comment]
```
  Caused by: java.lang.IllegalAccessError: Class object is null. Cannot generate template as it might obviously depend on reflection.
      at com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(JavaUtil.java:399)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
      at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
      ... 15 more
```
https://github.com/devonfw/cobigen/blob/f8f0dacc7178e8a1ae99c0755bf05aa4d8b331da/cobigen-templates/templates-devon4j/src/main/java/com/devonfw/cobigen/templates/devon4j/utils/JavaUtil.java#L399
