### ISSUE TITLE
Cobigen failed to generate code after doing adapt templates and updating templates

### ISSUE THREAD

**Issue by ravicm2** [devonfw/cobigen#1161]
### Expected behavior

Expected to generate code for the selected resources after adapting and updating templates. 

### Actual behavior

Fails with the below error mentioned in the comment

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  create an entity class as mentioned below
2.  right click -> cobigen -> adapt templates -> generate .

### Comments/Hints:
##Input:
public class EmployeeEntity {
  private String name;
  private Integer age;
  private String location;
}

##Selected Resources:
1. CRUD Rest service
2. CRUD SpringData Repository
3. CRUD UC logic
4. Entity Infrastructure
5. TOs

### Affected version:
* devon-ide version: 2020.04.001
* OS: Windows
* Browser: Chrome

**Comment by ravicm2** [comment]
**Fails with the below error:**

An error occurred while generating the template: C:\projects\devon\devonfw-ide-scripts-2020.04.001\workspaces\main\CobiGen_Templates\src\main\templates\crud_java_server_app\templates\java\${variables.rootPackage}\${variables.component}\common\api\${variables.entityName}.java.ftl (FreeMarker v2.3.29)
Java method "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(Class, String)" threw an exception when invoked on com.devonfw.cobigen.templates.devon4j.utils.JavaUtil object "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil@8c29c46"; see cause exception in the Java stack trace.

 

----
FTL stack trace ("~" means nesting-related):
    - Failed at: #assign compositeIdTypeVar = JavaUtil...  [in template "templates/java/${variables.rootPackage}/${variables.component}/common/api/${variables.entityName}.java.ftl" at line 5, column 1]
----
An error occurred while generating the template: C:\projects\devon\devonfw-ide-scripts-2020.04.001\workspaces\main\CobiGen_Templates\src\main\templates\crud_java_server_app\templates\java\${variables.rootPackage}\${variables.component}\common\api\${variables.entityName}.java.ftl (FreeMarker v2.3.29)
Java method "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(Class, String)" threw an exception when invoked on com.devonfw.cobigen.templates.devon4j.utils.JavaUtil object "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil@8c29c46"; see cause exception in the Java stack trace.

 

----
FTL stack trace ("~" means nesting-related):
    - Failed at: #assign compositeIdTypeVar = JavaUtil...  [in template "templates/java/${variables.rootPackage}/${variables.component}/common/api/${variables.entityName}.java.ftl" at line 5, column 1]
----
  com.devonfw.cobigen.api.exception.CobiGenRuntimeException: An error occurred while generating the template: C:\projects\devon\devonfw-ide-scripts-2020.04.001\workspaces\main\CobiGen_Templates\src\main\templates\crud_java_server_app\templates\java\${variables.rootPackage}\${variables.component}\common\api\${variables.entityName}.java.ftl (FreeMarker v2.3.29)
Java method "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(Class, String)" threw an exception when invoked on com.devonfw.cobigen.templates.devon4j.utils.JavaUtil object "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil@8c29c46"; see cause exception in the Java stack trace.

 

----
FTL stack trace ("~" means nesting-related):
    - Failed at: #assign compositeIdTypeVar = JavaUtil...  [in template "templates/java/${variables.rootPackage}/${variables.component}/common/api/${variables.entityName}.java.ftl" at line 5, column 1]
----
      at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:82)
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generateTemplateAndWriteFile(GenerationProcessorImpl.java:553)
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:415)
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:176)
      at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:94)
      at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:231)
      at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:190)
      at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:80)
      at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: freemarker.core._TemplateModelException: Java method "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(Class, String)" threw an exception when invoked on com.devonfw.cobigen.templates.devon4j.utils.JavaUtil object "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil@8c29c46"; see cause exception in the Java stack trace.

 

----
FTL stack trace ("~" means nesting-related):
    - Failed at: #assign compositeIdTypeVar = JavaUtil...  [in template "templates/java/${variables.rootPackage}/${variables.component}/common/api/${variables.entityName}.java.ftl" at line 5, column 1]
----
      at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
      at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
      at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
      at freemarker.core.MethodCall._eval(MethodCall.java:62)
      at freemarker.core.Expression.eval(Expression.java:101)
      at freemarker.core.Assignment.accept(Assignment.java:134)
      at freemarker.core.Environment.visit(Environment.java:331)
      at freemarker.core.Environment.visit(Environment.java:337)
      at freemarker.core.Environment.process(Environment.java:310)
      at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:78)
      ... 8 more
  Caused by: java.lang.ClassNotFoundException: javax.persistence.EmbeddedId
      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
      at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      at java.base/java.lang.Class.forName0(Native Method)
      at java.base/java.lang.Class.forName(Class.java:315)
      at com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.getReturnTypeOfMethodAnnotatedWith(JavaUtil.java:394)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
      at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
      at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
      ... 15 more
