### ISSUE TITLE
CobiGen has no consistent template conventions, custom templates not working, NPEs

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1169]
### Expected behavior

As a CobiGen user, I want to use my custom templates so that I can generate code specific for the needs of my projects.

### Actual behavior

CobiGen has no clearly designed and documented concept for templates and the template detection is full of hacks, inconsistencies and bugs:
* https://github.com/devonfw/cobigen/blob/master/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/utils/CobiGenUtils.java#L381
* https://github.com/devonfw/cobigen/blob/e296465791895f63a16618612127a25511849289/cobigen/cobigen-core-parent/cobigen-core/src/main/java/com/devonfw/cobigen/impl/util/TemplatesJarUtil.java#L29
* https://github.com/devonfw/cobigen/blob/4942eede166552fab4479faa617a0d1bf1b5cb0c/cobigen/cobigen-core-parent/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/constants/TemplatesJarConstants.java#L16

I get NPEs like:
```
java.lang.NullPointerException
at com.devonfw.cobigen.cli.utils.CobiGenUtils.initializeCobiGen(CobiGenUtils.java:89)
at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:123)
at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:1)
at picocli.CommandLine.executeUserObject(CommandLine.java:1680)
at picocli.CommandLine.access$900(CommandLine.java:144)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2038)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2005)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1872)
at picocli.CommandLine.execute(CommandLine.java:1801)
at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:43)
```

So to summarize what CobiGen currently demands:
* templates artifact name has to contain `devon4j` for CobiGen-CLI
* templates artifact name has to match `templates-([^-]+)-(\d+\.?)+.jar$`. Side note: I renamed my templates artifactId to `templates-devon4j` but then noticed that `templates-devon4j-2.5.0-snapshot.jar` does not match this regex.
* in Eclipse however the project has to be named `CobiGen_Templates`
* The templates have to be either in the root package or in the package `src.main.templates`

This is all historically grown and inconsistent, violating Java/maven conventions, etc.

IMHO CobiGen urgently requires a design for conventions and detection of templates.
My suggestion would be:
1. Define a new reasonable package namespace for templates. For simplicity I suggest `cobigen`
2. Remove any requirements for Maven GAV coordinates for templates as JAR files/dependencies
3. So in the end a templates project/module would have its templates in `src/main/resources/cobigen`
4. CobiGen would find Templates like this: `Thread.currentThread().getContextClassLoader().getResources("cobigen/triggers.xml")`
5. The `triggers.xml` should be a modular variant of the current `context.xml`.
6. For all matches of 4 the templates are loaded and in `triggers.xml` could be defined which plugins of cobigen are required that could be installed dynamically if not available.
7. If no match is found, a legacy machanism could apply for backward compatibility.

Also CobiGen CLI should allow to ease configuration for templates (instead of hacking a `pom.xml` just put a config in a defined place that can override the defaults).

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create custom templates and try generation with cobigen-cli by hacking `cobigen-cli/pom.xml`.

### Related/Dependent Issues

* #1109

### Affected version:

* OS: all

**Comment by MikeSchumacherCapgemini** [comment]
@hohwille  How exactly does the mentioned NPE happen?
Perhaps you can create a seperate issue detailing how you got it?
