### ISSUE TITLE
Javac assertion error during generation with CLI

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1176]
During generation I am getting this exception. Please note that I am not generating any Java output (only HTML and TypeScript). I am clueless what this error should tell me and where the actual problem could lie:
```
Exception in thread "main" java.lang.AssertionError
	at org.openjdk.tools.javac.util.Assert.error(Assert.java:155)
	at org.openjdk.tools.javac.util.Assert.check(Assert.java:46)
	at org.openjdk.tools.javac.parser.JavacParser.reportSyntaxError(JavacParser.java:481)
	at org.openjdk.tools.javac.parser.JavacParser.reportSyntaxError(JavacParser.java:462)
	at org.openjdk.tools.javac.parser.JavacParser.accept(JavacParser.java:511)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3555)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBodyDeclaration(JavacParser.java:3599)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceBody(JavacParser.java:3549)
	at org.openjdk.tools.javac.parser.JavacParser.classDeclaration(JavacParser.java:3398)
	at org.openjdk.tools.javac.parser.JavacParser.classOrInterfaceOrEnumDeclaration(JavacParser.java:3352)
	at org.openjdk.tools.javac.parser.JavacParser.typeDeclaration(JavacParser.java:3341)
	at org.openjdk.tools.javac.parser.JavacParser.parseCompilationUnit(JavacParser.java:3182)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:144)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:258)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:234)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:202)
	at com.devonfw.cobigen.cli.utils.ParsingUtils.formatJavaSources(ParsingUtils.java:244)
	at com.devonfw.cobigen.cli.commands.GenerateCommand.generate(GenerateCommand.java:350)
	at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:155)
	at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:46)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1680)
	at picocli.CommandLine.access$900(CommandLine.java:144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2038)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2005)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1872)
	at picocli.CommandLine.execute(CommandLine.java:1801)
	at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:43)
```

**Comment by hohwille** [comment]
https://github.com/devonfw/cobigen/blob/d693d9ee582bf4924b9cc67dd5e9fc2d79c255c2/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/commands/GenerateCommand.java#L350

So if `isJavaInput` is `true` CobiGen CLI wants to format the generated file as Java file no matter what format the file actually is.

**Comment by jdiazgon** [comment]
Right, that seems a bug. 

```Java
String extension = inputFile.getName().toLowerCase();
Boolean isJavaInput = extension.endsWith(".java");
```
If the input file is Java, it will try to format all the generated sources. The solution would be to check if the just generated file is a Java file, and only in that case format it.

**Comment by hohwille** [comment]
```
String extension = inputFile.getName().toLowerCase();
```
Another bug pattern. See here:
https://github.com/devonfw/devon4j/blob/develop/documentation/coding-conventions.asciidoc#encoding

**Comment by lilliCao** [comment]
Hi @hohwille what did you try to generate? and how? I don't think the problem is that cobigen will format all the generated files as java if the input is java file. Because I was actually able to generate .html .ts .css from a java input with cobigen-cli without any problem 
![cli](https://user-images.githubusercontent.com/15246597/83266005-92645e00-a1c2-11ea-9d33-bee03ecdfddb.PNG)
