### ISSUE TITLE
Not able to generate Java code with latest version of plugin

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/cobigen#1227]
### Expected behavior

As a user, I want to generate code using CobiGen.

### Actual behavior

Getting an error  as below:
CobiGen_Templates does not exist
Java Model Exception: Java Model Status [CobiGen_Templates does not exist]
at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2525)
at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2382)
at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2466)
at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClasspathURLs(ClassLoaderUtil.java:60)
at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClassLoader(ClassLoaderUtil.java:41)
at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:185)
at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:181)
at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:79)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install latest version of ide
2. Create new project using devon4j
3. Create new entity class
4. Right click on entity class and in CobiGen option click on Generate
5. Select options 
CRUD REST service, CRUD SpringData Repository, CRUD UC logic, Entity Infrastructure and TO's
6. Click next and finish.

### Affected version:

* OS: Windows

**Comment by jdiazgon** [comment]
I'm still facing this issue. I think I'm using latest CobiGen version as you can see below:

![image](https://user-images.githubusercontent.com/31688036/95446896-40e29180-0961-11eb-890e-930b94cdff5e.png)

The workaround is importing the templates to the current workspace (adapt templates), but most of CobiGen users doesn't know this.
