### ISSUE TITLE
NullPointerException during Health Check

### ISSUE THREAD

**Issue by j4yk** [devonfw/cobigen#1229]
### Expected behavior

As a developer, I want to run the CobiGen Health Check as part of the tutorial at https://github.com/devonfw/jump-the-queue/wiki/ so that I can continue the tutorial and be sure to have everything set up correctly. (Actually I am preparing for a training.) The Health Check should show a dialog box about checking the templates with an OK and an Advanced Health Check button.

The Health Check is mentioned on this page:  in https://github.com/devonfw/jump-the-queue/wiki/devon4j-components.

### Actual behavior

An error message appears instead of the dialog.

```
An unexpected error occurred! Templates were not found.

Reason:

java.lang.NullPointerException
  java.lang.NullPointerException
  	at com.devonfw.cobigen.eclipse.healthcheck.HealthCheckDialog.execute(HealthCheckDialog.java:76)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.HealthCheckHandler.execute(HealthCheckHandler.java:31)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
  	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Follow the tutorial up to that step.
2. Right-click on the AccessCodeEntity.java file > CobiGen > Health Check...

### Comments/Hints:

After invoking the Health Check and before the error appeared, I was presented with a prompt by the Windows Firewall that some program (I don't remember which) wants to serve on the network. I denied the request (my default choice unless I know that my machine must serve something for outside of localhost).

The error appeared after first downloading the templates. I don't remember whether first the templates were downloaded or first the Firewall prompt appeared.

Despite the error message, the download of the templates (templates-devon4j) was reported to have been successful ("Downloaded successfully!"). I can also re-run the download via CobiGen > Update Templates..., again successfully. It will not solve the NullPointerException.

I downloaded and "installed" the devonfw-ide just today and used [this download](https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.tools.ide&a=devonfw-ide-scripts&v=LATEST&p=tar.gz).

Please let me know if I can provide further information.

### Affected version:

* OS: Windows 7
* Browser: Chrome

**Comment by j4yk** [comment]
If I go on with the tutorial nevertheless, CobiGen will go on to report that the templates did not exist during the "Generate..." step:

```
An eclipse internal exception occurred during processing:
CobiGen_Templates does not exist
  If this problem persists please report it to the CobiGen developers.

Reason:
CobiGen_Templates does not exist.

CobiGen_Templates does not exist
  CobiGen_Templates does not exist
  Java Model Exception: Java Model Status [CobiGen_Templates does not exist]
  	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
  	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2525)
  	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2382)
  	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2466)
  	at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClasspathURLs(ClassLoaderUtil.java:60)
  	at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClassLoader(ClassLoaderUtil.java:41)
  	at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:185)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:181)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:79)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```
