### ISSUE TITLE
Error while trying to generate Code with cobigen on Katacoda

### ISSUE THREAD

**Issue by denise-khuu** [devonfw/cobigen#1307]
### Expected behavior

It should generate code from one single java class based on existing templates. 

### Actual behavior
This Error-Message occurs
## [ERROR] Invalid configuration of context
com.devonfw.cobigen.api.exception.InvalidConfigurationException: No valid templates can be found. Please configure your cobigen configuration file properly or place the templates in cobigen home directory. Creating CobiGen instance aborted.
        at com.devonfw.cobigen.impl.CobiGenFactory.create(CobiGenFactory.java:62) ~[cobigen.jar:na]
        at com.devonfw.cobigen.cli.utils.CobiGenUtils.initializeCobiGen(CobiGenUtils.java:61) ~[cobigen.jar:na]
        at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:128) ~[cobigen.jar:na]
        at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:51) ~[cobigen.jar:na]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933) ~[cobigen.jar:na]
        at picocli.CommandLine.access$1100(CommandLine.java:145) ~[cobigen.jar:na]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) ~[cobigen.jar:na]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) ~[cobigen.jar:na]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) ~[cobigen.jar:na]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) ~[cobigen.jar:na]
        at picocli.CommandLine.execute(CommandLine.java:2058) ~[cobigen.jar:na]
        at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:45) ~[cobigen.jar:na]
java.lang.NullPointerException
        at java.base/java.nio.file.Path.of(Path.java:197)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:131)
        at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:51)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:45)
### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Follow the steps stated in this Tutorial https://katacoda.com/denisekhuu/scenarios/cobigen-cli
2. At step 6 while using the plugin via the context menu you will see this error message

**Comment by GuentherJulian** [comment]
When running 'devon cobigen adapt-templates' before the 'devon generate' command it works. Then the folder .cobigen/templates is not empty either. Is it necessary to run 'adapt-templates' first? When we created the tutorial, it wasn't.
I can reproduce it on my machine with a fresh devon installation, too.

**Comment by maybeec** [comment]
No, it should not. Possibly, there is an issue with the latest refactoring 
@lilliCao could you have a look and maybe think about how we can get this into an automated test?
