### ISSUE TITLE
Generation fails with "CobiGen_Templates does not exist"

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1369]
### Expected behavior

As a cobigen user, I want it to work out of the box in a new IDE installation and project so that I have a seamless jumpstart.

### Actual behavior

I started generation and followed the cobigen workflow to download the templates.
Then I could choose the increments so the templates are somewhere available to cobigen.
However, after choosing an increment and starting the generation (click on `Finish`), I get this error:

```
CobiGen_Templates does not exist
  CobiGen_Templates does not exist
  Java Model Exception: Java Model Status [CobiGen_Templates does not exist]
  	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
  	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2525)
  	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2382)
  	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2466)
  	at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClasspathURLs(ClassLoaderUtil.java:60)
  	at com.devonfw.cobigen.eclipse.common.tools.ClassLoaderUtil.getProjectClassLoader(ClassLoaderUtil.java:41)
  	at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:185)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:181)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:79)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install latest devonfw-ide
2. start eclipse
3. create new devon4j project
4. import that project into eclipse
5. create a new entity (`MyExampleEntity extends ApplicationPersistenceEntity` in `dataaccess.api` package).
6. Right click on it and choose `CobiGen > Generate`
7. Confirm to download templates
8. choose any increment (e.g. `TOs` or `Entity infrastructure`)
9. Click `Finish`

### Related/Dependent Issues

* #1240

### Comments/Hints:

As CobiGen can show the increments and give a preview of what is to be generated, it must have the templates at hand already. However, I do not have a `CobiGen_Templates` Project in my Eclipse.
If that is required for generation then the Download step is lacking to import this project into Eclipse and CobiGen is therefore not ready to be used by new users.

### Affected version:

Eclipse IDE for Java Developers (includes Incubating components)

Version: 2021-03 (4.19.0)
Build id: 20210312-0638

  CobiGen - FreeMarker Template Engine	7.0.0	com.devonfw.cobigen.tempeng-freemarker	devonfw
  CobiGen - HTML Plug-in	7.0.0	com.devonfw.cobigen.htmlplugin	devonfw
  CobiGen - Java Plug-in	7.1.0	com.devonfw.cobigen.javaplugin	devonfw
  CobiGen - JSON Plug-in	7.0.0	com.devonfw.cobigen.jsonplugin	devonfw
  CobiGen - Open API Plug-in	7.1.0	com.devonfw.cobigen.openapiplugin	devonfw
  CobiGen - Property File Plug-In	7.1.0	com.devonfw.cobigen.propertyplugin	devonfw
  CobiGen - Text Merger Plug-in	7.1.1	com.devonfw.cobigen.textmerger	devonfw
  CobiGen - TypeScript Plug-in	7.1.0	com.devonfw.cobigen.tsplugin	devonfw
  CobiGen - Velocity Template Engine	7.0.0	com.devonfw.cobigen.tempeng-velocity	devonfw
  CobiGen - XML Plug-In	7.0.0	com.devonfw.cobigen.xmlplugin	devonfw
  CobiGen Eclipse Plug-in	7.1.0	com.devonfw.cobigen.eclipse.feature.feature.group	devonfw Team

**Comment by hohwille** [comment]
First, please check if the version of CobiGen I was using is maybe already outdated and the bug might already been fixed.
Howerver, then I would need further instructions as I already selected `Check for updates` and got no updates for CobiGen.

**Comment by hohwille** [comment]
As a Workaround I selected `Adapt templates` what gave me a sequence of several popups including one that the templates needed again to be downloaded. However, at the end `CobiGen_Templates` project was available in Eclipse and now it is working.
However, this is an obvious pitfall for new users and CobiGen should work without such hurdles and pain points as many users give up early on the first error.
