### ISSUE TITLE
OutOfMemoryError while adapting the template in Eclipse

### ISSUE THREAD

**Issue by sujithmn** [devonfw/cobigen#1372]
Getting the below error while adapting the template.

![image](https://user-images.githubusercontent.com/986334/126103131-89b78f24-7cb6-4b3b-b874-3f080e0caabd.png)

Heap size used:  -Xms256m-Xmx2048m

**Comment by maybeec** [comment]
Hi sujith, could you please right click on the stack trace in the window, copy and paste here?

**Comment by maybeec** [comment]
Please also comply to the bug issue template. There is way to less information. The templates have been added to be used.

**Comment by maybeec** [comment]
Some more information (would have loved to see this on error creation @sujith-mn )
StackTrace:
```
Java heap space
Java heap space
  java.lang.OutOfMemoryError: Java heap space
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.initOffsets(ZipPath.java:431)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getNameCount(ZipPath.java:124)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.resolve0(ZipPath.java:572)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getResolved(ZipPath.java:563)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:458)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(ZipPath.java:740)
  	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:292)
  	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
  	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
  	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
  	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.extractArchive(ExtractTemplatesUtil.java:143)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.processJar(ExtractTemplatesUtil.java:103)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.extractTemplates(ExtractTemplatesUtil.java:72)
  	at com.devonfw.cobigen.eclipse.common.tools.ResourcesPluginUtil.processJar(ResourcesPluginUtil.java:231)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.AdaptTemplatesHandler.execute(AdaptTemplatesHandler.java:85)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
```

Only occurs if you delete the $HOME/.cobigen folder to cleanup all previously downloaded templates.

**Comment by maybeec** [comment]
The stacktrace seems to be different every time:

```
Java heap space
Java heap space
  java.lang.OutOfMemoryError: Java heap space
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.resolve(ZipPath.java:310)
  	at jdk.zipfs/jdk.nio.zipfs.ZipPath.resolve(ZipPath.java:296)
  	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.iteratorOf(ZipFileSystem.java:444)
  	at jdk.zipfs/jdk.nio.zipfs.ZipDirectoryStream.iterator(ZipDirectoryStream.java:69)
  	at java.base/java.nio.file.FileTreeWalker$DirectoryNode.<init>(FileTreeWalker.java:78)
  	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:310)
  	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.extractArchive(ExtractTemplatesUtil.java:143)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.processJar(ExtractTemplatesUtil.java:103)
  	at com.devonfw.cobigen.impl.util.ExtractTemplatesUtil.extractTemplates(ExtractTemplatesUtil.java:72)
  	at com.devonfw.cobigen.eclipse.common.tools.ResourcesPluginUtil.processJar(ResourcesPluginUtil.java:231)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.AdaptTemplatesHandler.execute(AdaptTemplatesHandler.java:85)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$$Lambda$349/0x00000001006f3c40.handleEvent(Unknown Source)
```

**Comment by maybeec** [comment]
Could be related to https://stackoverflow.com/a/23861949
One example of worst programming in JDK I have seen.

**Comment by jan-vcapgemini** [comment]
While checking the current sources.jar I've found out that it includes a folder with a simple dot "." as its folder name.
After removing the folder from the sources.jar the infinite loop in walkFileTree was fixed and the CobiGen_Templates project was successfully created.

**Comment by jan-vcapgemini** [comment]
We've found out what is causing the "." folder.
https://github.com/devonfw/cobigen/blob/9420c2dd9bd7b76c27018a9498ff9fd52b988eec/cobigen-templates/pom.xml#L35-L36
A possible fix would be to use a fixed resource like this:
```
<resource>
        <directory>src/main/resources/META-INF</directory>
        <targetPath>META-INF</targetPath>
</resource>
```
