### ISSUE TITLE
Generate with CRUD devon4j Server CRUD REST services fails with any input

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1406]
### Expected behavior

As a CobiGen Eclipse user, I want to generate a CRUD REST service artifact.

### Actual behavior
When generating from an input entity or openAPI file, following merge error occurs:

`Unable to merge the patch generated by template D:\devon_ide\workspaces\junit-workspace\CobiGen_Templates\src\main\templates\crud_openapi_java_server_app\templates\java\${variables.rootPackage}\${variables.component#lower_case}\service\api\rest\${variables.component#cap_first}RestService.java.ftl into file C:\Users\username\AppData\Local\Temp\cobigen-12921793936326071041\src\main\java\sampledatamanagement\service\api\rest\SampledatamanagementRestService.java: The syntax of the base file is invalid. Error in line: 1 / column: 9: syntax error @[1,9]
Unable to merge the patch generated by template D:\devon_ide\workspaces\junit-workspace\CobiGen_Templates\src\main\templates\crud_openapi_java_server_app\templates\java\${variables.rootPackage}\${variables.component#lower_case}\service\api\rest\${variables.component#cap_first}RestService.java.ftl into file C:\Users\username\AppData\Local\Temp\cobigen-12921793936326071041\src\main\java\sampledatamanagement\service\api\rest\SampledatamanagementRestService.java: The syntax of the base file is invalid. Error in line: 1 / column: 9: syntax error @[1,9]
  com.devonfw.cobigen.api.exception.MergeException: Unable to merge the patch generated by template D:\devon_ide\workspaces\junit-workspace\CobiGen_Templates\src\main\templates\crud_openapi_java_server_app\templates\java\${variables.rootPackage}\${variables.component#lower_case}\service\api\rest\${variables.component#cap_first}RestService.java.ftl into file C:\Users\username\AppData\Local\Temp\cobigen-12921793936326071041\src\main\java\sampledatamanagement\service\api\rest\SampledatamanagementRestService.java: The syntax of the base file is invalid. Error in line: 1 / column: 9: syntax error @[1,9]
  	at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:525)
  	at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:212)
  	at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:99)
  	at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:82)
  	at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:215)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:179)
  	at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:78)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: com.thoughtworks.qdox.parser.ParseException: syntax error @[1,9]
  	at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1790)
  	at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1912)
  	at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1771)
  	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
  	at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
  	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
  	at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:89)
  	at com.devonfw.cobigen.javaplugin.merger.libextension.ModifyableClassLibraryBuilder.addSource(ModifyableClassLibraryBuilder.java:42)
  	at com.devonfw.cobigen.javaplugin.inputreader.JavaParserUtil.getFirstJavaClass(JavaParserUtil.java:76)
  	at com.devonfw.cobigen.javaplugin.inputreader.JavaParserUtil.getFirstJavaClass(JavaParserUtil.java:44)
  	at com.devonfw.cobigen.javaplugin.merger.JavaMerger.merge(JavaMerger.java:76)
  	at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:510)
  	... 7 more
`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a simple project with an example OpenAPI file
2. Run CobiGen Generate
3. Choose f.e. CRUD REST services

### Affected version:

*   CobiGen Eclipse Plug-in	2021.8.3
*   CobiGen - OpenAPI Plug-in	2021.8.2
*   CobiGen - Java Plug-in	2021.8.2

### Acceptance Criteria

Sprint2:

* [ ] need for configuration adaption to make it possible to declare variableAssignments to be mandatory causing an intermediate error on missing variable. 
* [ ] please add website link into error message in case of openapi missing variables to help the user to help himself
* [ ] documentation update

**Comment by maybeec** [comment]
Sounds to me like very odd error message / handling. Any thoughts on that to Dave this issue not again?

**Comment by maybeec** [comment]
* [ ] need for configuration adaption to make it possible to declare variableAssignments to be mandatory causing an intermediate error on missing variable. 
* [ ] please add website link into error message in case of openapi missing variables to help the user to help himself
