### ISSUE TITLE
CLI on Linux is missing dependencies from templates

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1450]
### Expected behavior

As a CobiGen CLI user, I want to generate code for my project using the current templates.

### Actual behavior
When generating code for springdata-repository increment, the following error occurs:

`[ERROR] Further reported error:
com.devonfw.cobigen.api.exception.CobiGenRuntimeException: An error occurred while generating the template: /src/main/templates/crud_java_server_app/templates/java/${variables.rootPackage}/${variables.component}/logic/api/to/${variables.entityName}Eto.java.ftl (FreeMarker v2.3.29)
        at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:77)
        at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generateTemplateAndWriteFile(GenerationProcessorImpl.java:614)
        at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:537)
        at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:212)
        at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:99)
        at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:82)
        at com.devonfw.cobigen.cli.commands.GenerateCommand.generate(GenerateCommand.java:270)
        at com.devonfw.cobigen.cli.commands.GenerateCommand.doAction(GenerateCommand.java:117)
        at com.devonfw.cobigen.cli.commands.CommandCommons.call(CommandCommons.java:36)
        at com.devonfw.cobigen.cli.commands.CommandCommons.call(CommandCommons.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:37)
Caused by: freemarker.core._TemplateModelException: Java method "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.castJavaPrimitives(Class, String)" threw an exception when invoked on com.devonfw.cobigen.templates.devon4j.utils.JavaUtil object "com.devonfw.cobigen.templates.devon4j.utils.JavaUtil@6d33a66e"; see cause exception in the Java stack trace.
FTL stack trace ("~" means nesting-related):
        - Failed at: ${JavaUtil.castJavaPrimitives(classOb...  [in template "templates/java/${variables.rootPackage}/${variables.component}/logic/api/to/${variables.entityName}Eto.java.ftl" at line 34, column 67]
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:261)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:65)
        at freemarker.core.MethodCall._eval(MethodCall.java:62)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:373)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:337)
        at freemarker.core.Environment.visit(Environment.java:337)
        at freemarker.core.Environment.process(Environment.java:310)
        at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:74)
        ... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/ClassUtils
        at com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.boxJavaPrimitives(JavaUtil.java:69)
        at com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.castJavaPrimitives(JavaUtil.java:212)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
        at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
        at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:61)
        ... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.ClassUtils
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 44 common frames omitted`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install a fresh devonfw-ide
2. Run `devon cobigen`
3. cd to 'workspaces/main'
4. Create an example project using: `devon java create com.example.application.cobigenexample`
5. Create a folder structure using: `mkdir -p cobigenexample/core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api`
6. Create a new CustomerEntity.java within the api folder with this content: https://raw.githubusercontent.com/devonfw-tutorials/tutorials/main/cobigen/files/CustomerEntity.java
7. cd to workspaces/cobigenexample
8. Run `mvn clean install -DskipTests`
9. Run `cobigen generate core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api/CustomerEntity.java -i springdata-repository`

### Comments/Hints:
Adding following dependency to the core/pom.xml and rebuilding the project fixes the issue:
```
<dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>3.12.0</version>
</dependency>
```
It looks like CLI is not resolving the dependencies of the templates project.

### Affected version:

* CobiGen CLI 2021.12.001

**Comment by jan-vcapgemini** [comment]
It looks like this issue also occurs on Windows.

**Comment by jan-vcapgemini** [comment]
It also appears that this issue only occurs when CLI loads the templates from a jar instead of the unpacked CobiGen_Templates folder.

**Comment by jan-vcapgemini** [comment]
Issue still occurs on Linux.

**Comment by jan-vcapgemini** [comment]
It appears that the ClassLoader is successful in loading the lang3 dependency.

[DEBUG] Initiating CobiGen
[INFO ] Searching for plug-ins at classloader jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc
[INFO ] Loading plug-in activators...
[ERROR] At least one plug-in should be registered of type GeneratorPluginActivator
[INFO ] Loading template engines...
[ERROR] At least one plug-in should be registered of type TextTemplateEngine
[INFO ] Searching for plug-ins at classloader java.net.URLClassLoader@233795b6
[DEBUG] URL Classloader with URLs:
[DEBUG]   * file:/mnt/c/Users/username/Documents/devon-ide/conf/.m2/repository/com/devonfw/cobigen/javaplugin/2021.12.005/javaplugin-2021.12.005.jar
[DEBUG]   * file:/mnt/c/Users/username/Documents/devon-ide/conf/.m2/repository/com/devonfw/cobigen/javaplugin-model/2021.12.005/javaplugin-model-2021.12.005.jar
[DEBUG]   * file:/mnt/c/Users/username/Documents/devon-ide/conf/.m2/repository/com/devonfw/cobigen/core-api/2021.12.005/core-api-2021.12.005.jar
[DEBUG]   * **file:/mnt/c/Users/username/Documents/devon-ide/conf/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar**

It still fails with the same error message though:

**Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/ClassUtils**
        at com.devonfw.cobigen.templates.devon4j.utils.JavaUtil.boxJavaPrimitives(JavaUtil.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
        at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
        at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:61)
        ... 35 more

**java.lang.ClassNotFoundException: org.apache.commons.lang3.ClassUtils at** java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 44 common frames omitted
