### ISSUE TITLE
Exception while generating code using open api yml file from eclipse

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/cobigen#1451]
After adapting the template change the directory to be generated in the properties file.
Right click on the yml file and generate, below exception occurs.

```
An error occurred while generating the template: C:\projects\startupkit\workspaces\main\CobiGen_Templates\src\main\templates\crud_openapi_angular_client_app\templates\src\app\${variables.etoName#lower_case}\${variables.etoName#lower_case}-dialog\${variables.etoName#lower_case}-dialog.component.html.ftl (FreeMarker v2.3.29)
com.devonfw.cobigen.api.exception.CobiGenRuntimeException: An error occurred while generating the template: C:\projects\startupkit\workspaces\main\CobiGen_Templates\src\main\templates\crud_openapi_angular_client_app\templates\src\app\${variables.etoName#lower_case}\${variables.etoName#lower_case}-dialog\${variables.etoName#lower_case}-dialog.component.html.ftl (FreeMarker v2.3.29)
at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:77)
at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generateTemplateAndWriteFile(GenerationProcessorImpl.java:614)
at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:537)
at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:212)
at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:99)
at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:82)
at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:215)
at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:179)
at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:78)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> JavaUtil [in template "templates/src/app/${variables.etoName#lower_case}/${variables.etoName#lower_case}-dialog/${variables.etoName#lower_case}-dialog.component.html.ftl" at line 7, column 15]
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

FTL stack trace ("~" means nesting-related):
- Failed at: ${JavaUtil.getAngularType(property.ty... [in template "templates/src/app/${variables.etoName#lower_case}/${variables.etoName#lower_case}-dialog/${variables.etoName#lower_case}-dialog.component.html.ftl" at line 7, column 13]

at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
at freemarker.core.NonHashException.<init>(NonHashException.java:49)
at freemarker.core.Dot._eval(Dot.java:48)
at freemarker.core.Expression.eval(Expression.java:101)
at freemarker.core.MethodCall._eval(MethodCall.java:55)
at freemarker.core.Expression.eval(Expression.java:101)
at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
at freemarker.core.Environment.visit(Environment.java:367)
at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
at freemarker.core.Environment.visit(Environment.java:331)
at freemarker.core.Environment.visit(Environment.java:337)
at freemarker.core.Environment.process(Environment.java:310)
at com.devonfw.cobigen.tempeng.freemarker.FreeMarkerTemplateEngine.process(FreeMarkerTemplateEngine.java:74)
... 9 more

```

**Comment by jan-vcapgemini** [comment]
In which Version does this error occur?
Please check if the CobiGen_Templates/target/classes/com/devonfw/cobigen/templates/devon4j/utils/JavaUtil.class is present.
Does this error only occur when changing the properties files or when using the default templates too?

**Comment by GuentherJulian** [comment]
Cannot reproduce the error with the current CobiGen version.
@sujith-mn do you still have the problem. If so, please give a more detailed description to reproduce it.

**Comment by maybeec** [comment]
I had a similar case. What I did:

1. install fresh devonfw ide
2. on console run `devon eclipse` to open eclipse
3. setup new devon4j application based on devon4j archetype
4. create basic Entity with two fields in the general package corresponding to devon4j naming conventions
5. on console run `devon cobigen` on console
6. run `devon`
7. navigate to core module of the created devon4j project
8. run `cg g <created entity>`
