### ISSUE TITLE
Enable reading of new configuration

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1457]
As a cobigen developer, I want to be able to read both versions of configurations (the old templates folder as well as the new developed in #1456) so that we don't disturb existing users by breaking their installation.

**Comment by GuentherJulian** [comment]
Tested the new context configuration reader in the CLI.
**All results are as expected.**

1. With the new template structure (context.xml in template subfolders):
    Successful generation
2. With the old template structure (context.xml in the root folder of all templates):
    Successful generation
3. With both configurations (context.xml in root and subfolders):
    Exception:
```
←[31m←[1mcom.devonfw.cobigen.api.exception.InvalidConfigurationException: C:\Users\jgunther\.cobigen\templates\CobiGen_Templates\src\main\templates\context.xml:
You are using an old configuration of the templates in addition to new ones. Please make sure this is not the case as both at the same time are not supported. For more details visit this wiki page: https://github.com/devonfw/cobigen/wiki/cobigen-core_configuration#update-old-config←[21m←[39m←[0m
←[3m    at com.devonfw.cobigen.impl.config.reader.ContextConfigurationReader.<init>(ContextConfigurationReader.java:91)←[23m←[0m
←[3m    at com.devonfw.cobigen.impl.config.ContextConfiguration.readConfiguration(ContextConfiguration.java:49)←[23m←[0m
```

4. With no context.xml:
    Exception:
```
←[31m←[1mcom.devonfw.cobigen.api.exception.InvalidConfigurationException: C:\Users\jgunther\.cobigen\templates\CobiGen_Templates\src\main\templates\context.xml:
Could not find any context configuration file.←[21m←[39m←[0m
←[3m    at com.devonfw.cobigen.impl.config.reader.ContextConfigurationReader.<init>(ContextConfigurationReader.java:83)←[23m←[0m
←[3m    at com.devonfw.cobigen.impl.config.ContextConfiguration.readConfiguration(ContextConfiguration.java:49)←[23m←[0m
←[3m    at com.devonfw.cobigen.impl.config.ContextConfiguration.<init>(ContextConfiguration.java:38)←[23m←[0m
```
