### ISSUE TITLE
Eclipse generate throws InvocationTargetException if context.xml is present in template sets and root

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1496]
### Expected behavior

As a CobiGen Eclipse user, I want CobiGen to cancel the generate process and display a proper error message when a conflict between the new and old template directory structure exists.

### Actual behavior
Eclipse tries to load the templates and throws an InvocationTargetException.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a simple maven project with an example OpenApi file to generate from
2. Import the templates from the latest master into your workspace
3. Copy a random context.xml from one of the template sets into the root of CobiGen_Templates
4. Start a generate from the OpenApi file

### Comments/Hints:
The HealthCheck of Eclipse will detect this issue and display the expected error message.

### Affected version:

* Eclipse Plug-in 2021.12.007-SNAPSHOT

**Comment by GuentherJulian** [comment]
This seems to be a general problem of the error dialog of the Eclipse generate command and does not only refer to the new configuration structure.
With Cobigen 2021.12.006 and an invalid 'old' configuration structure (e.g. without context.xml) the dialog does not show a correct message either

![eclipse_error](https://user-images.githubusercontent.com/69513769/157076724-3bee1bb8-f4ec-4220-ae2e-3ed186cd7803.PNG)

```
InvocationTargetException
java.lang.reflect.InvocationTargetException
  java.lang.reflect.InvocationTargetException
  	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)
  	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:468)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.GenerateHandler.execute(GenerateHandler.java:42)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
  	at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
  	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
  Caused by: org.eclipse.swt.SWTException: Invalid thread access
  	at org.eclipse.swt.SWT.error(SWT.java:4907)
  	at org.eclipse.swt.SWT.error(SWT.java:4822)
  	at org.eclipse.swt.SWT.error(SWT.java:4793)
  	at org.eclipse.swt.widgets.Display.error(Display.java:1272)
  	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:827)
  	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1490)
  	at com.devonfw.cobigen.eclipse.common.tools.ExceptionHandler.openInvalidConfigurationErrorDialog(ExceptionHandler.java:77)
  	at com.devonfw.cobigen.eclipse.common.tools.ExceptionHandler.handle(ExceptionHandler.java:38)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.GenerateJob.run(GenerateJob.java:106)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by maybeec** [comment]
This means you are trying to open for example an display in a non ui thread. To do so, you should search for code like Display.getDefault to see how you can execute ui code in a non ui thread

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1496?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini

**Comment by maybeec** [comment]
Hint: https://github.com/devonfw/cobigen/blob/e79ace2758460a9d86ed9057b486dd7eca6b47ed/cobigen-eclipse/cobigen-eclipse/src/com/devonfw/cobigen/eclipse/common/tools/ExceptionHandler.java#L77 should not access `Display`. Better let shell being passed, which has been retrieved beforehand already.
