### ISSUE TITLE
Track issues with devonfw-ide after latest 2022.08.001 release

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1586]
### Expected behavior

As a CobiGen developer, I expect the latest version of devonfw ide to be working properly.

### Actual behavior
Several bugs occur during the installation and in the latest version of Eclipse.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Update devonfw ide using: `devon ide update all`

### Comments/Hints:
We need a list of issues which occur during the update and after the update.

### Affected version:

* devonfw-ide 2022.08.001

**Comment by EduardKrieger** [comment]
I got 2 Issues:

-  After upgrading the IDE and eclipse, opening files in the project explorer is not working anymore. 
- Installation of the plugin **SWTBot** does not work with the command `devon eclipse add-plugin swtbot` and returns an error. Installation within the **Install New Software..** feature from eclipse is working.

**Comment by quantumfate** [comment]
I ran across this issue while following the [mgmt setup guide](https://github.com/devonfw/cobigen/wiki/mgmt_ide-setup).

Specifically by executing the command `devon project setup cobigen`.


(Executed in Powershell)
```bash
Success: run command mvn                                                                                                                             
Starting eclipse import for /c/projects/cobigentest/workspaces/main/cobigen into workspace main at /c/projects/cobigentest/workspaces/main            
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.concurrent                                                                      org.eclipse.m2e.logback.configuration: Activated before the state location was initialized. Retry after the state location is initialized.            
10:47:47.474 [main] DEBUG o.e.m.c.i.p.r.ProjectRegistryRefreshJob - Queued refresh request: []                                                        org.eclipse.m2e.logback.configuration: Logback config file: C:\projects\cobigentest\workspaces\main\.metadata\.plugins\org.eclipse.m2e.logback.configuration\logback.2.0.0.20220705-1221.xml                                                                                                                
org.eclipse.m2e.logback.configuration: Initializing logback                                                                                           
Buildfile: C:/projects/cobigentest/scripts/lib_script/import.xml                                                                                                                                                                                                                                            default:                                                                                                                                                                                                                                                                                                    BUILD FAILED                                                                                                                                          C:\projects\cobigentest\scripts\lib_script\import.xml:12: BUG! exception in phase 'semantic analysis' in source unit 'C:\projects\cobigentest\scripts\lib_script\import.groovy' Unsupported class file major version 63                                                                                             at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:884)                                        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)                                                                      at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)                                                                             
at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)                                                                      at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)                                                        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)                                                      at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)                                                                               
at groovy.lang.GroovyShell.parseClass(GroovyShell.java:530)                                                                                           
at groovy.lang.GroovyShell.parse(GroovyShell.java:542)                                                                                                
at groovy.lang.GroovyShell.parse(GroovyShell.java:574)                                                                                                
at org.codehaus.groovy.ant.Groovy.parseAndRunScript(Groovy.java:501)                                                                                  
at org.codehaus.groovy.ant.Groovy.execGroovy(Groovy.java:460)                                                                                         
at org.codehaus.groovy.ant.Groovy.execute(Groovy.java:323)                                                                                            
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)                                                                               at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                              at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                         
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)                                                                         
at org.apache.tools.ant.Task.perform(Task.java:350)                                                                                                   
at org.apache.tools.ant.Target.execute(Target.java:449)                                                                                               
at org.apache.tools.ant.Target.performTasks(Target.java:470)                                                                                          
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)                                                                               
at org.apache.tools.ant.Project.executeTarget(Project.java:1374)                                                                                      
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)                                                                
at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)                                            at org.apache.tools.ant.Project.executeTargets(Project.java:1264)                                                                                     
at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:716)                                                                
at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:573)                                                                
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                              at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                         
at org.eclipse.ant.core.AntRunner.run(AntRunner.java:506)                                                                                             
at org.eclipse.ant.core.AntRunner.start(AntRunner.java:603)                                                                                           
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)                                                                   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)                                           at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)                                                    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)                                                                       
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)                                                                       
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                              at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                         
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)                                                                                   
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)                                                                                          
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)                                                                                              
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)                                                                                     
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63                                                                        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)                                                                                       
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)                                                                                       
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)                                                                                       
at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)                                                                                       
at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)                                                                 at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)                                                           at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)                                                 at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)                                                            at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)                                                              at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)                                                                 
at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:498)                                                                        
at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)                                                                    
at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)                                                                 
at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:717)                                                                at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)                                        ... 41 more                                                                                                                                                                                                                                                                                         Total time: 2 seconds                                                                                                                                 
Command 'eclipse import cobigen cobigen' failed with exit code 150
```


A similar issue but slightly differen while executing the mentioned command above: (executed in CMD)
```
default:                                                                                                                                                                                                                                                                                                                                                                                                        BUILD FAILED                                                                                                                                                                                            C:\projects\cobigentest\scripts\lib_script\import.xml:12: BUG! exception in phase 'semantic analysis' in source unit 'C:\projects\cobigentest\scripts\lib_script\import.groovy' Unsupported class file major version 63                                                                                                                                                                                                 at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:884)                                                                                          at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:623)                                                                                                                        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)                                                                                                                               at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)                                                                                                                        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)                                                                                                          at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)                                                                                                        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)                                                                                                                                 at groovy.lang.GroovyShell.parseClass(GroovyShell.java:530)                                                                                                                                             at groovy.lang.GroovyShell.parse(GroovyShell.java:542)                                                                                                                                                  at groovy.lang.GroovyShell.parse(GroovyShell.java:574)                                                                                                                                                  at org.codehaus.groovy.ant.Groovy.parseAndRunScript(Groovy.java:501)                                                                                                                                    at org.codehaus.groovy.ant.Groovy.execGroovy(Groovy.java:460)                                                                                                                                           at org.codehaus.groovy.ant.Groovy.execute(Groovy.java:323)                                                                                                                                              at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)                                                                                                                                 at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                                                                                at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                                                                           at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)                                                                                                                           at org.apache.tools.ant.Task.perform(Task.java:350)                                                                                                                                                     at org.apache.tools.ant.Target.execute(Target.java:449)                                                                                                                                                 at org.apache.tools.ant.Target.performTasks(Target.java:470)                                                                                                                                            at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)                                                                                                                                 at org.apache.tools.ant.Project.executeTarget(Project.java:1374)                                                                                                                                        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)                                                                                                                  at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)                                                                                              at org.apache.tools.ant.Project.executeTargets(Project.java:1264)                                                                                                                                       at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:716)                                                                                                                  at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:573)                                                                                                                  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                                                                                at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                                                                           at org.eclipse.ant.core.AntRunner.run(AntRunner.java:506)                                                                                                                                               at org.eclipse.ant.core.AntRunner.start(AntRunner.java:603)                                                                                                                                             at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)                                                                                                                     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)                                                                                             at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)                                                                                                      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)                                                                                                                         at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)                                                                                                                         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)                                                                                                at java.base/java.lang.reflect.Method.invoke(Method.java:578)                                                                                                                                           at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)                                                                                                                                     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)                                                                                                                                            at org.eclipse.equinox.launcher.Main.run(Main.java:1467)                                                                                                                                                at org.eclipse.equinox.launcher.Main.main(Main.java:1440)                                                                                                                                       Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63                                                                                                                          at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)                                                                                                                                         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)                                                                                                                                         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)                                                                                                                                         at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)                                                                                                                                         at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)                                                                                                                   at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)                                                                                                             at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)                                                                                                   at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)                                                                                                              at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)                                                                                                                at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:869)                                                                                                                   at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:498)                                                                                                                          at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1430)                                                                                                                      at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:261)                                                                                                                   at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:717)                                                                                                                  at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)                                                                                          ... 41 more                                                                                                                                                                                                                                                                                                                                                                                             Total time: 2 seconds                                                                                                                                                                                   Command 'eclipse import cobigen cobigen' failed with exit code 102
```
