### ISSUE TITLE
Not successful generation when using """ in repos

### ISSUE THREAD

**Issue by dariusz-piechnik-cap** [devonfw/cobigen#1589]
### Expected behavior

As a CobiGen Eclipse user, I want to have successful generation on entitites that are using repo with custom methods. Those custom methods are annotated with @Query("""...""").

### Actual behavior

The generation process fails due to invalid characters: """(Multiline string).

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Annotate any custom method in Repository for given _Entity_ with @Query("""
...
""")
2. Try to generate files with Eclipse CobiGen for given _Entity_
3. Error arrives.

### Comments/Hints:

`Unable to merge the patch generated by template <PATH>Repository.java: The syntax of the base file is invalid. Error in line: 44 / column: 7: syntax error @[44,7]
Unable to merge the patch generated by template <PATH>Repository.java.ftl into file <PATH>Repository.java: The syntax of the base file is invalid. Error in line: 44 / column: 7: syntax error @[44,7]
  com.devonfw.cobigen.api.exception.MergeException: Unable to merge the patch generated by template <PATH>Repository.java.ftl into file <PATH>Repository.java: The syntax of the base file is invalid. Error in line: 44 / column: 7: syntax error @[44,7]
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:370)
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:155)
      at com.devonfw.cobigen.impl.generator.CobiGenImpl.generate(CobiGenImpl.java:82)
      at com.devonfw.cobigen.eclipse.generator.CobiGenWrapper.generate(CobiGenWrapper.java:219)
      at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.performGeneration(GenerateSelectionJob.java:189)
      at com.devonfw.cobigen.eclipse.wizard.generate.control.GenerateSelectionJob.run(GenerateSelectionJob.java:80)
      at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
  Caused by: com.thoughtworks.qdox.parser.ParseException: syntax error @[44,7]
      at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:1775)
      at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1897)
      at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:1756)
      at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:232)
      at com.thoughtworks.qdox.library.SourceLibrary.parse(SourceLibrary.java:190)
      at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:94)
      at com.thoughtworks.qdox.library.SourceLibrary.addSource(SourceLibrary.java:89)
      at com.devonfw.cobigen.javaplugin.merger.libextension.ModifyableClassLibraryBuilder.addSource(ModifyableClassLibraryBuilder.java:39)
      at com.devonfw.cobigen.javaplugin.inputreader.JavaParserUtil.getFirstJavaClass(JavaParserUtil.java:60)
      at com.devonfw.cobigen.javaplugin.inputreader.JavaParserUtil.getFirstJavaClass(JavaParserUtil.java:25)
      at com.devonfw.cobigen.javaplugin.merger.JavaMerger.merge(JavaMerger.java:68)
      at com.devonfw.cobigen.impl.generator.GenerationProcessorImpl.generate(GenerationProcessorImpl.java:354)
      ... 6 more`

### Affected version:
com.devonfw.cobigen.eclipse_5.1.0
com.devonfw.cobigen.javaplugin_2.2.0.jar

I tried to upgrade as it is described Eclipse Integration doc, but no new version was found.

* OS: Windows

**Comment by hohwille** [comment]
Actually looks like a bug in [QDox](https://github.com/paul-hammant/qdox). Update to latest version should be the first try.

**Comment by KHucklenbroich** [comment]
Multi line string literals haven't been implemented until java 15

**Comment by Lur1an** [comment]
I have succeded in replicating the issue by adding a multiline String in a @Query annotation in the repository.
Upgrading the qdox version does not fix this, I suppose qdox is built to work with Java <= 11.
CobiGen will NOT be able to MERGE into Java files that use language features introduced after Java 11 LTS.
@jan-vcapgemini @maybeec

**Comment by jan-vcapgemini** [comment]
This issue can be closed as it will be continued in #1607
