### ISSUE TITLE
Adapt templates Eclipse adaption

### ISSUE THREAD

**Issue by mdukhan** [devonfw/cobigen#1622]
### Expected behavior

As a Eclipse CobiGen user, I want update and adapt Templates command from Eclipse to work properly. 

### Actual behavior

Update and adapt templates command do not work and the following error will be thrown:

```Could not download file from https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.cobigen&a=templates-devon4j&v=LATEST&c=sources
Could not download file from https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.cobigen&a=templates-devon4j&v=LATEST&c=sources
  com.devonfw.cobigen.api.exception.CobiGenRuntimeException: Could not download file from https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.devonfw.cobigen&a=templates-devon4j&v=LATEST&c=sources
  	at com.devonfw.cobigen.api.util.TemplatesJarUtil.downloadJar(TemplatesJarUtil.java:87)
  	at com.devonfw.cobigen.api.util.TemplatesJarUtil.downloadLatestDevon4jTemplates(TemplatesJarUtil.java:101)
  	at com.devonfw.cobigen.eclipse.common.tools.ResourcesPluginUtil.downloadJar(ResourcesPluginUtil.java:178)
  	at com.devonfw.cobigen.eclipse.workbenchcontrol.handler.AdaptTemplatesHandler.execute(AdaptTemplatesHandler.java:80)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
  	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
  Caused by: java.nio.file.NoSuchFileException: C:\Projects\testNewDevon\conf\.cobigen\templates\templates-devon4j-2021.12.006-sources.jar
  	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
  	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
  	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
  	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
  	at java.base/java.nio.file.Files.copy(Files.java:3067)
  	at com.devonfw.cobigen.api.util.TemplatesJarUtil.downloadJar(TemplatesJarUtil.java:78)
  	... 47 more
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Right click in Eclipse, choose CobiGen -> Adapt Templates

### Related/Dependent Issues
#1509 

### Affected version:

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by cedricarnauld123** [comment]
I couldn't preproduce the Bug. I use devon with version 2022.12.001 and CobiGen version 2021.12.006. 
@mdukhan can you try again to test the Bug or provide some more information.
